apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - image: shreyasnhcool2345/analytics-service:latest
        name: analytics-service
        ports:
        - containerPort: 5500
