apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - image: yourdockerhub/billing-service:v1.7.2
        name: billing-service
        ports:
        - containerPort: 4000
