apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://prod-db:5432/mydb
        image: yourdockerhub/payment-service:v1.4.3
        name: payment-service
        ports:
        - containerPort: 8001
