apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuing-service
  template:
    metadata:
      labels:
        app: queuing-service
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://analytics-db:5432/analytics
        image: yourdockerhub/queuing-service:v1.5.1
        name: queuing-service
        ports:
        - containerPort: 6043
