apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: user-service
        image: yourdockerhub/user-service:v2.1.0
        name: user-service
        ports:
        - containerPort: 8000
